create database kc;
use kc;

CREATE TABLE `department` (
  `DEPT_ID` int NOT NULL AUTO_INCREMENT,
  `DEPT_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `employee` (
  `EMP_ID` int NOT NULL AUTO_INCREMENT,
  `EMP_NAME` varchar(45) DEFAULT NULL,
  `DEPT_ID` int NOT NULL,
  PRIMARY KEY (`EMP_ID`),
  UNIQUE KEY `DEPT_ID_UNIQUE` (`DEPT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `address` (
  `ADDR_ID` int NOT NULL AUTO_INCREMENT,
  `ADDR_TYPE` varchar(45) DEFAULT NULL,
  `ADDRESS1` varchar(45) DEFAULT NULL,
  `ADDRESS2` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `COUNTRY` varchar(45) DEFAULT NULL,
  `PINCODE` int DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `EMP_ID` int DEFAULT NULL,
  PRIMARY KEY (`ADDR_ID`),
  KEY `empid_foreignkey_idx` (`EMP_ID`),
  CONSTRAINT `empid_foreignkey` FOREIGN KEY (`EMP_ID`) REFERENCES `employee` (`EMP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `employeesalary` (
  `S_ID` int NOT NULL AUTO_INCREMENT,
  `SALARY` int NOT NULL,
  `PF` int NOT NULL,
  `EMP_ID` int NOT NULL,
  PRIMARY KEY (`S_ID`),
  UNIQUE KEY `S_ID_UNIQUE` (`S_ID`),
  UNIQUE KEY `EMP_ID_UNIQUE` (`EMP_ID`),
  CONSTRAINT `empsal_foreignkey` FOREIGN KEY (`EMP_ID`) REFERENCES `employee` (`EMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
